#!/bin/bash -l
#SBATCH -J'Ex178_hifiasm'            # this names the job
#SBATCH --ntasks=32                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o outlog_Ex178                       # this will create an output log
#SBATCH -e errlog_Ex178                       # this will create an error log
#SBATCH -t 30:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step

number_of_threads=32  #Set this to the number of tasts "ntasks" from sbatch

#We need to set our file path to be where all of our documents are.
# Typically we will submit our slurm.job file from the right directory.  However
# it is probably good to move to the right folder just in case!
#run_files_top_directory="./home/cmallory/Genetic_analysis/bd_genetics_analysis/bowtie_alignment"  # This variable can be changed to hold the directory where stuff is!



#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current dir to location that the job was submitted from.    

fastq_files_csv_path="/home/cmallory/Genetic_analysis/bd_pac_bio2026/batch_1_file_names.txt"
echo $fastq_files_csv_path

echo "the current path now is: $SLURM_SUBMIT_DIR"

# This is the location of the fastq file we will use!
fastq_file="/home/cmallory/Genetic_analysis/bd_pac_bio2026/fastq/m84066_260515_190348_s3.Ex178.7_7.fastq"

start_time=$(date '+%Y-%m-%d %H:%M:%S')


base_name="$(basename "$fastq_file" .fastq)"

run_results_folder="/home/cmallory/Genetic_analysis/bd_pac_bio2026/hifiasm/hifiasm_homo-""$base_name""-""$start_time"

mkdir "$run_results_folder"

#setup output_folder
save_file="$run_results_folder""/""hifiasm""$todays_date""-""${base_name}"".asm"

echo "[$start_time] Assembling $fastq_file"
echo "Results will be saved in $save_file"


./hifiasm -o $save_file -t$number_of_threads --hg-size 24m -l0 $fastq_file

end_time=$(date '+%Y-%m-%d %H:%M:%S')
echo "[$end_time] of $base_name complete!"
echo "=========================================="




/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID
