#!/bin/bash -l
#SBATCH -J'hifiasm_homozygot_run_3'            # this names the job
#SBATCH --ntasks=32                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o outlog_homo_3                       # this will create an output log
#SBATCH -e errlog_homo_3                       # this will create an error log
#SBATCH -t 30:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step

number_of_threads=32  #Set this to the number of tasts "ntasks" from sbatch

#We need to set our file path to be where all of our documents are.
# Typically we will submit our slurm.job file from the right directory.  However
# it is probably good to move to the right folder just in case!
#run_files_top_directory="./home/cmallory/Genetic_analysis/bd_genetics_analysis/bowtie_alignment"  # This variable can be changed to hold the directory where stuff is!



#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current dir to location that the job was submitted from.    

fastq_files_csv_path="/home/cmallory/Genetic_analysis/bd_pac_bio2026/batch_1_file_names.txt"
echo $fastq_files_csv_path

echo "the current path now is: $SLURM_SUBMIT_DIR"



# Now check if the fastq files listed in the text file exist
# IT figures out the full path to all the files of interest.  If it finds those files it adds the full
# path to the fastq_files list for use later
run_results_folder="/home/cmallory/Genetic_analysis/bd_pac_bio2026/hifiasm_homo-2026-06-01_16-52-00"
fastq_file="/home/cmallory/Genetic_analysis/bd_pac_bio2026/fastq/m84066_260515_190348_s3.Ex179.8_8.fastq"


echo "Lets start our assembly!"
# Write loop for all the fastq files sacved in the fastq_files list.
#  Create new output file name and location name etc should be in the output folder called run_results_folder
# Then run the assembly code.
#  Create a few debugging comments to save in the run output file.

start_time=$(date '+%Y-%m-%d %H:%M:%S')


base_name="$(basename "$fastq_file" .fastq)"

#make output file
save_file="$run_results_folder""/""hifiasm""$todays_date""-""${base_name}"".asm"

touch "$save_file"
echo "[$start_time] Assembling $fastq_file"
echo "Results will be saved in $save_file"


./hifiasm/hifiasm -o $save_file -t$number_of_threads --hg-size 24m -l0 $fastq_file

end_time=$(date '+%Y-%m-%d %H:%M:%S')
echo "[$end_time] of $base_name complete!"
echo "=========================================="




/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID
